# Generated by Django 5.2.4 on 2025-07-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="customer_code",
            field=models.CharField(
                default="XXXXXXXXXXXXXX", max_length=20, verbose_name="Customer Code"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="received_from",
            field=models.CharField(
                default="XXXXXXXXXXXXXX", max_length=50, verbose_name="Received From"
            ),
        ),
    ]
