# Generated by Django 5.2.4 on 2025-07-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_transaction_receipt_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='receipt_url',
            field=models.CharField(blank=True, default='XXXXXXXXXXXXX', max_length=200, null=True, verbose_name='Receipt URL'),
        ),
    ]
