# Generated by Django 5.2.5 on 2025-09-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0009_payment_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="customer_code",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Customer Code"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="first_name",
            field=models.CharField(max_length=20, null=True, verbose_name="First Name"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="ip_address",
            field=models.CharField(max_length=20, null=True, verbose_name="IP Address"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="last_name",
            field=models.CharField(max_length=20, null=True, verbose_name="Last Name"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="receipt_url",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Receipt URL"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="received_from",
            field=models.CharField(max_length=50, verbose_name="Received From"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="txn_reference",
            field=models.CharField(
                db_index=True, max_length=15, verbose_name="Transaction Reference"
            ),
        ),
    ]
