# Generated by Django 5.2.5 on 2025-09-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0010_alter_transaction_customer_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="receipt_hash",
            field=models.CharField(
                default=1,
                editable=False,
                max_length=64,
                unique=True,
                verbose_name="Receipt Hash",
            ),
            preserve_default=False,
        ),
    ]
