# Generated by Django 5.2.4 on 2025-07-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
