# Generated by Django 5.2.4 on 2025-07-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_department_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='bank_code',
            field=models.CharField(default='000', max_length=10),
        ),
    ]
