# Generated by Django 5.2.4 on 2025-07-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_department_dept_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to Logo'),
        ),
        migrations.AddField(
            model_name='department',
            name='president_signature_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to President Signature'),
        ),
        migrations.AddField(
            model_name='department',
            name='secretary_signature_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link to Financial Secretary Signature'),
        ),
    ]
