# Generated by Django 5.2.5 on 2025-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_department_logo_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="is_verified",
            field=models.BooleanField(
                default=False, verbose_name="Verification Status"
            ),
        ),
    ]
