# Generated by Django 5.2.5 on 2025-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_department_options_department_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AddField(
            model_name="department",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="temp_uploads/"),
        ),
        migrations.AddField(
            model_name="department",
            name="president_signature",
            field=models.ImageField(blank=True, null=True, upload_to="temp_uploads/"),
        ),
        migrations.AddField(
            model_name="department",
            name="secretary_signature",
            field=models.ImageField(blank=True, null=True, upload_to="temp_uploads/"),
        ),
    ]
