# Generated by Django 5.2.5 on 2025-09-08 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_department_options_department_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="account_name",
            field=models.CharField(
                default="XXXXXXXXXX", max_length=200, verbose_name="Bank Account Name"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
        ),
        migrations.AlterField(
            model_name="department",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Department ID",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="sub_account_code",
            field=models.CharField(
                default="XXXXXXXXXXXX", max_length=20, verbose_name="Sub Account Code"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Last updated"),
        ),
    ]
