# Generated by Django 5.2.5 on 2025-09-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_department_account_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="id",
            new_name="department_id",
        ),
    ]
