# Generated by Django 5.2.5 on 2025-09-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rename_id_department_department_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="department_id",
            new_name="dept_id",
        ),
    ]
