# Generated by Django 5.2.5 on 2025-09-08 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_rename_department_id_department_dept_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["-updated_at", "-created_at"],
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
    ]
