# Generated by Django 5.2.5 on 2025-09-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_alter_department_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="department",
            old_name="dept_id",
            new_name="id",
        ),
    ]
